# NL Lab - Database config
spring.datasource.url=jdbc:postgresql://postgres.jcfbtafdpyeptviorddm:Soyunapayso@aws-1-us-east-2.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# SMTP Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=crtainboy@gmail.com
spring.mail.password=leoopmtwyjhtwtug
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Server
server.port=${PORT:8080}
