# NL Lab - Database config
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?ssl=true&sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.jcfbatfdpyeptviorddm}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Propiedades robustas de HikariCP para forzar SSL e integrarse bien con Supabase
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require
spring.datasource.hikari.initialization-fail-timeout=0

# Connection Logging
logging.level.org.hibernate.orm.jdbc.dialect=DEBUG
logging.level.org.hibernate.engine.jdbc.connections=DEBUG

# SMTP Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=crtainboy@gmail.com
spring.mail.password=leoopmtwyjhtwtug
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Server
server.port=${PORT:8080}
